# Generated by Django 5.0.6 on 2024-05-10 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('Adventure', models.CharField(max_length=100, verbose_name='Adventure')),
                ('Animation', models.CharField(max_length=100, verbose_name='Animation')),
                ('Children', models.CharField(max_length=100, verbose_name='Children')),
                ('Comedy', models.CharField(max_length=100, verbose_name='Comedy')),
                ('Fantasy', models.CharField(max_length=100, verbose_name='Fantasy')),
                ('Romance', models.CharField(max_length=100, verbose_name='Romance')),
                ('Drama', models.CharField(max_length=100, verbose_name='Drama')),
                ('Action', models.CharField(max_length=100, verbose_name='Action')),
                ('Crime', models.CharField(max_length=100, verbose_name='Crime')),
                ('Thriller', models.CharField(max_length=100, verbose_name='Thriller')),
                ('Horror', models.CharField(max_length=100, verbose_name='Horror')),
                ('Mystery', models.CharField(max_length=100, verbose_name='Mystery')),
                ('Sci_Fi', models.CharField(max_length=100, verbose_name='Sci_Fi')),
                ('IMAX', models.CharField(max_length=100, verbose_name='IMAX')),
                ('Documentary', models.CharField(max_length=100, verbose_name='Documentary')),
                ('War', models.CharField(max_length=100, verbose_name='War')),
                ('Musical', models.CharField(max_length=100, verbose_name='Musical')),
                ('Western', models.CharField(max_length=100, verbose_name='Western')),
                ('Film_Noir', models.CharField(max_length=100, verbose_name='Film_Noir')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Adventure', models.CharField(max_length=100, verbose_name='Adventure')),
                ('Animation', models.CharField(max_length=100, verbose_name='Animation')),
                ('Children', models.CharField(max_length=100, verbose_name='Children')),
                ('Comedy', models.CharField(max_length=100, verbose_name='Comedy')),
                ('Fantasy', models.CharField(max_length=100, verbose_name='Fantasy')),
                ('Romance', models.CharField(max_length=100, verbose_name='Romance')),
                ('Drama', models.CharField(max_length=100, verbose_name='Drama')),
                ('Action', models.CharField(max_length=100, verbose_name='Action')),
                ('Crime', models.CharField(max_length=100, verbose_name='Crime')),
                ('Thriller', models.CharField(max_length=100, verbose_name='Thriller')),
                ('Horror', models.CharField(max_length=100, verbose_name='Horror')),
                ('Mystery', models.CharField(max_length=100, verbose_name='Mystery')),
                ('Sci_Fi', models.CharField(max_length=100, verbose_name='Sci_Fi')),
                ('IMAX', models.CharField(max_length=100, verbose_name='IMAX')),
                ('Documentary', models.CharField(max_length=100, verbose_name='Documentary')),
                ('War', models.CharField(max_length=100, verbose_name='War')),
                ('Musical', models.CharField(max_length=100, verbose_name='Musical')),
                ('Western', models.CharField(max_length=100, verbose_name='Western')),
                ('Film_Noir', models.CharField(max_length=100, verbose_name='Film_Noir')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
