# Generated by Django 5.0.6 on 2024-05-10 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_profile_action_alter_profile_adventure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='Action',
            field=models.BooleanField(verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Adventure',
            field=models.BooleanField(verbose_name='Adventure'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Animation',
            field=models.BooleanField(verbose_name='Animation'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Children',
            field=models.BooleanField(verbose_name='Children'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Comedy',
            field=models.BooleanField(verbose_name='Comedy'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Crime',
            field=models.BooleanField(verbose_name='Crime'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Documentary',
            field=models.BooleanField(verbose_name='Documentary'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Drama',
            field=models.BooleanField(verbose_name='Drama'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Fantasy',
            field=models.BooleanField(verbose_name='Fantasy'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Film_Noir',
            field=models.BooleanField(verbose_name='Film_Noir'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Horror',
            field=models.BooleanField(verbose_name='Horror'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='IMAX',
            field=models.BooleanField(verbose_name='IMAX'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Musical',
            field=models.BooleanField(verbose_name='Musical'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Mystery',
            field=models.BooleanField(verbose_name='Mystery'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Romance',
            field=models.BooleanField(verbose_name='Romance'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Sci_Fi',
            field=models.BooleanField(verbose_name='Sci_Fi'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Thriller',
            field=models.BooleanField(verbose_name='Thriller'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='War',
            field=models.BooleanField(verbose_name='War'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Western',
            field=models.BooleanField(verbose_name='Western'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Action',
            field=models.CharField(max_length=100, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Adventure',
            field=models.CharField(max_length=100, verbose_name='Adventure'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Animation',
            field=models.CharField(max_length=100, verbose_name='Animation'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Children',
            field=models.CharField(max_length=100, verbose_name='Children'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Comedy',
            field=models.CharField(max_length=100, verbose_name='Comedy'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Crime',
            field=models.CharField(max_length=100, verbose_name='Crime'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Documentary',
            field=models.CharField(max_length=100, verbose_name='Documentary'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Drama',
            field=models.CharField(max_length=100, verbose_name='Drama'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Fantasy',
            field=models.CharField(max_length=100, verbose_name='Fantasy'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Film_Noir',
            field=models.CharField(max_length=100, verbose_name='Film_Noir'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Horror',
            field=models.CharField(max_length=100, verbose_name='Horror'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='IMAX',
            field=models.CharField(max_length=100, verbose_name='IMAX'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Musical',
            field=models.CharField(max_length=100, verbose_name='Musical'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Mystery',
            field=models.CharField(max_length=100, verbose_name='Mystery'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Romance',
            field=models.CharField(max_length=100, verbose_name='Romance'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Sci_Fi',
            field=models.CharField(max_length=100, verbose_name='Sci_Fi'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Thriller',
            field=models.CharField(max_length=100, verbose_name='Thriller'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='War',
            field=models.CharField(max_length=100, verbose_name='War'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Western',
            field=models.CharField(max_length=100, verbose_name='Western'),
        ),
    ]
